from alerts.telegram.client import send


async def cmd_help() -> None:
    await send(
        "🤖 *Signal Engine v5 — Commands*\n\n"
        "*ESSENTIALS*\n"
        "/status   — bot status + coin states\n"
        "/queue    — active zones + trades\n"
        "/scan     — manual scan\n\n"
        "*TRADING*\n"
        "/trades          — open positions\n"
        "/position ETH   — deep dive\n"
        "/health          — health check\n"
        "/balance         — account balance\n"
        "/profit          — profit summary\n\n"
        "*MARKET*\n"
        "/btc · /coin ETH · /funding · /fear\n\n"
        "*CONTENT*\n"
        "/pending · /brief · #N · /discard N\n\n"
        "*PERFORMANCE*\n"
        "/pnl · /daily · /stats · /grade · /history\n"
        "/backtest BTC · /performance\n\n"
        "*ADAPTATION*\n"
        "/adaptations — view all changes\n"
        "/freeze      — pause adaptations\n"
        "/unfreeze    — resume adaptations\n"
        "/rollback X  — revert parameter X\n"
        "/approve N   — approve recommendation N\n"
        "/reject N    — reject recommendation N\n"
        "/version     — current parameters\n"
        "/analysis    — run analysis now\n\n"
        "*OTHER*\n"
        "/ml · /mode · /help\n"
    )